nextcloud:
  image: jatula/nextcloud:11.0.1
  links:
    - db_nextcloud:db_nextcloud
  volumes:
    - data:/var/www/html
  ports:
    - "8080:80"
db_nextcloud:
  image: mariadb:10
  volumes:
    - db_data:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    - MYSQL_PASSWORD=password